import type { ReactNode } from 'react';
import 'styles/style.scss';

type Props = {
  children: ReactNode;
};

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: Props): JSX.Element {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
